### ISSUE TITLE
Getting Two Errors When Trying to Compile.

### ISSUE THREAD

**Issue by Bj007pro** [alxbrn/kdmapper-1803-1903#1]
When I try to compile I get 2 unresolved errors, and can't find out exactly what they are:
![image](https://user-images.githubusercontent.com/24400879/68302888-b61d6500-0107-11ea-9769-5928ccb497ac.png)

**Comment by alxbrn** [comment]
You are missing a linker import, most likely because you are not building in x64 Release.
