### ISSUE TITLE
How does ClearMmUnloadedDrivers even work

### ISSUE THREAD

**Issue by bugproof** [alxbrn/kdmapper-1803-1903#2]
Shouldn't this be called after the driver was unloaded (from your mapped driver)?

https://github.com/alxbrn/kdmapper-1803-1903/blob/2c357a5a13501a310287b4899deeefb93aa5d880/kdmapper/intel_driver.cpp#L39-L42

It seems pointless but maybe I'm not getting it? Wouldn't it add it again after you call `ControlService` with `SERVICE_CONTROL_STOP`

**Comment by alxbrn** [comment]
I'm not the original author, this is just a fork. So I would suggest you ask this question on the main branch.
